version: '3'

services:
  ci-build:
    image: microsoft/dotnet:latest
    volumes:
      - .:/src
    working_dir: /src
    command: /bin/bash -c "dotnet restore ./netcoredemo.sln && dotnet publish ./netcoredemo.sln -c Release -o ./obj/Docker/publish"
